[project]
name = "player1dev"
version = "0.1.0"

[dependencies]
fastapi = "*"
flet = "*"
jinja2 = "*"
lxml = "*"
markdown = "*"
passlib = "*"
pymongo = "*"
python-dotenv = "*"
python-jwt = "*"
uvicorn = "*"
wheel = "*"